cart/urls.py
from django.urls import path

from cart.views import CartItemsListView, AddItemView, EmptyCart, GetCartItemsTotalQuantity
from cart.views import CartAdd, CartRemove, CartDetail

app_name = 'cart'

urlpatterns = [
    path('', CartDetail.as_view(), name='cart_detail'),
    path('add/<product_id>/', CartAdd.as_view(), name='cart_add'),
    path('remove/<product_id>/', CartRemove.as_view(), name='cart_remove'),

    path('cart/', CartItemsListView.as_view(), name='cart'),
    path('add-product/', AddItemView.as_view(), name='add_item'),
    #path('cart-items-total-quantity/', GetCartItemsTotalQuantity.as_view(), name='cart-items-quantity'),
    path('empty-cart/', EmptyCart.as_view(), name='empty-cart'),
]

midgard/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView, RedirectView

from accounts.views import SignupView, LogoutUserView, LoginUserView, ProfileView
from cart.views import CartItemsListView, AddItemView, GetCartItemsTotalQuantity, EmptyCart

urlpatterns = [
                  path('admin/', admin.site.urls),
                  #path('cart', TemplateView.as_view(template_name='cart.html'), name='cart'),
                  path('checkout', TemplateView.as_view(template_name='checkout.html'), name='checkout'),
                  path('contact', TemplateView.as_view(template_name='contact.html'), name='contact'),
                  path('signup', SignupView.as_view(), name='signup'),
                  path('logout', LogoutUserView.as_view(), name='logout'),
                  path('login', LoginUserView.as_view(), name='login'),
                  path('oauth', include('social_django.urls', namespace='social')),
                  path('', RedirectView.as_view(url='shop')),
                  path('shop/', include('product.urls', namespace='shop')),
                  path('profile/', ProfileView.as_view(), name='profile'),
                  #path('cart/', CartItemsListView.as_view(), name='cart'),
                  path(r'cart/', include('cart.urls', namespace='cart')),
                  path(r'orders/', include('orders.urls', namespace='orders')),
                  path('add-product/', AddItemView.as_view(), name='add_item'),
                  #path('cart-items-total-quantity/', GetCartItemsTotalQuantity.as_view(), name='cart-items-quantity'),
                  path('empty-cart/', EmptyCart.as_view(), name='empty-cart'),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
                      path('__debug__/', include(debug_toolbar.urls)),

                      # For django versions before 2.0:
                      # url(r'^__debug__/', include(debug_toolbar.urls)),

                  ] + urlpatterns

orders/urls.py
from django.urls import path
from .views import *

app_name = 'orders'

urlpatterns = [
        path('show/<order_id>/', OrderDetailView.as_view(), name='order_detail'),
        path('create/', OrderCreateView.as_view(), name='order_create'),
        path('', OrderListView.as_view(), name='order_list'),
]

product/urls.py
from django.urls import path

from product.views import MainPageView, ProductListView, ProductDetailView

app_name = 'product'

urlpatterns = (
    path('', MainPageView.as_view(), name='main'),
    path('all/', ProductListView.as_view(), name='products-list'),
    path('product/<int:pk>/about', ProductDetailView.as_view(), name='about'),
)

cart/models.py
from django.db import models

from accounts.models import Profile
from product.models import Product


class CartManager(models.Manager):

    def get_cart_items_total_quantity(self, request):
        cart_items = Cart.objects.get(user=request.user).cart_items.all()
        total_quantity = 0
        for cart_item in cart_items:
            total_quantity += cart_item.quantity
        return total_quantity

    def get_cart_items(self, user):
        return self.get().cart_items.all()

    def empty_cart(self, user):
        self.get(user=user).cart_items.all().delete()


class Cart(models.Model):
    user = models.OneToOneField(Profile, null=True, blank=True, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

    objects = CartManager()


class CartItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    cart = models.ForeignKey('Cart', on_delete=models.CASCADE, related_name='cart_items')

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.views import View
from django.views.generic import ListView, TemplateView

from cart.models import Cart


class CartItemsListView(ListView):
    template_name = 'cart.html'
    model = Cart
    context_object_name = 'cart_items'

    def get_queryset(self):
        return Cart.objects.get_cart_items(self.request.user)


class EmptyCart(View):

    def get(self, request):
        Cart.objects.empty_cart(self.request.user)
        return redirect('cart')


class AddItemView(TemplateView):

    def render_to_response(self, context, **response_kwargs):
        if self.request.user.is_authenticated:
            cart, cart_created = Cart.objects.get_or_create(user=self.request.user)
            product_id = self.request.GET.get('product_id')
            item, created = cart.cart_items.get_or_create(product_id=product_id)
            if not created:
                item.quantity = item.quantity + 1
                item.save()
            data = {'cart_total_items_quantity': Cart.objects.get_cart_items_total_quantity(self.request)}
            return JsonResponse(data)
        else:
            data = {'unauthorized_error': 'true'}
            return JsonResponse(data)


class GetCartItemsTotalQuantity(TemplateView):

    def render_to_response(self, context, **response_kwargs):
        data = {'cart_total_items_quantity': Cart.objects.get_cart_items_total_quantity(self.request)}
        return JsonResponse(data)


class EmptyCart(View):

    def get(self, request):
        Cart.objects.get(user=self.request.user).cart_items.all().delete()
        return redirect('cart')

    # - - - - - - - - - - - - - - - - - - -- -


from django.shortcuts import render, redirect, get_object_or_404

from product.models import Product
from .cart import Cart as Cart2
from .forms import CartAddProductForm


class CartDetail(LoginRequiredMixin, View):
    login_url = 'login'
    # Переделать этот метод для работы с моделью Cart не получилось( много сложных ошибок/ КАЮСЬ!
    def get(self, request):
        cart = Cart2(request)
        for item in cart:
            item['update_quantity_form'] = CartAddProductForm(
                initial={
                    'quantity': item['quantity'],
                    'update': True
                })
        return render(request, 'cart/detail.html', {'cart': cart})


class CartAdd(View):

    def get(self, request, product_id):
        cart = Cart2(request)
        product = get_object_or_404(Product, id=product_id)
        cart.add(product=product,
                 update_quantity=False)
        return redirect('cart:cart_detail')

    def post(self, request, product_id):
        cart = Cart2(request)
        product = get_object_or_404(Product, id=product_id)
        form = CartAddProductForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            cart.add(product=product,
                     quantity=cd['quantity'],
                     update_quantity=cd['update'])
        return redirect('cart:cart_detail')


class CartRemove(View):

    def get(self, request, product_id):
        cart = Cart2(request)
        product = get_object_or_404(Product, id=product_id)
        cart.remove(product)
        return redirect('cart:cart_detail')

cart/templates/cart/detail.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block title %}
    Your shopping cart
{% endblock %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-sm-12 col-md-10 col-md-offset-1">
             <h1>Your shopping cart</h1>
            <table class="table table-hover">
                <thead>
                <tr>
                    <th>Product</th>
                    <th>Quantity</th>
                    <th class="text-center">Price</th>
                    <th class="text-center">Total</th>
                    <th> </th>
                </tr>
                </thead>
                <tbody>
                {% for item in cart %}
                    {% with product=item.product %}
                        <tr>
                            <td class="col-sm-8 col-md-6">
                                <div class="media">
                                    <a class="thumbnail pull-left" href="{{ product.get_absolute_url }}">
                                        <img class="media-object"
                                             src="{% if product.main_photo %}{{ product.main_photo.url }}
                                                 {% endif %}"
                                             style="width: 72px; height: 72px;">
                                    </a>
                                    <div class="media-body">
                                        <h4 class="media-heading"><a
                                                href="{{ product.get_absolute_url }}">{{ product.name }}</a></h4>
                                        <span>Статус: </span><span class="text-success"><strong>в наличии</strong></span>
                                    </div>
                                </div>
                            </td>
                            <td class="col-sm-1 col-md-1" style="text-align: center">
                                <form action="{% url 'cart:cart_add' product.id %}" method="post">
                                    {% csrf_token %}
                                    {% bootstrap_field item.update_quantity_form.quantity%}
                                    {% bootstrap_field item.update_quantity_form.update %}
                                    {% buttons %}
                                        <button type="submit" class="btn btn-success btn-product">
                                            Обновить
                                        </button>
                                    {% endbuttons %}
                                </form>
                            </td>

                            <td class="col-sm-1 col-md-1 text-center"><strong>${{ item.price }}</strong></td>
                            <td class="col-sm-1 col-md-1 text-center"><strong>${{ item.total_price }}</strong></td>

                            <td class="col-sm-1 col-md-1">
                                <a href="{% url 'cart:cart_remove' product.id %}" class="btn btn-danger">
                                    <i class="glyphicon glyphicon-remove" aria-hidden="true"></i> Удалить
                                </a>
                            </td>
                        </tr>
                    {% endwith %}
                {% endfor %}
                <tr>
                    <td>  </td>
                    <td>  </td>
                    <td>  </td>
                    <td><h3>Total</h3></td>
                    <td class="text-right"><h3><strong>${{ cart.get_total_price }}</strong></h3></td>
                </tr>
                <tr>
                    <td>  </td>
                    <td>  </td>
                    <td>  </td>
                    <td>
                        <a href="{% url 'product:products-list' %}" class="btn btn-default">
                            Продолжить покупки <i class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></i>
                        </a>
                    </td>
                    <td>
                        <a href="{% url 'orders:order_create' %}" class="btn btn-default">Оформить Заказ <i
                                class="glyphicon glyphicon-play" aria-hidden="true"></i>
                        </a>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>

{% endblock %}