cart/urls.py
from django.urls import path

from cart.views import CartItemsListView, AddItemView, EmptyCart, GetCartItemsTotalQuantity
from cart.views import CartAdd, CartRemove, CartDetail

app_name = 'cart'

urlpatterns = [
    path('', CartDetail.as_view(), name='cart_detail'),
    path('add/<product_id>/', CartAdd.as_view(), name='cart_add'),
    path('remove/<product_id>/', CartRemove.as_view(), name='cart_remove'),

    path('cart/', CartItemsListView.as_view(), name='cart'),
    path('add-product/', AddItemView.as_view(), name='add_item'),
    #path('cart-items-total-quantity/', GetCartItemsTotalQuantity.as_view(), name='cart-items-quantity'),
    path('empty-cart/', EmptyCart.as_view(), name='empty-cart'),
]

midgard/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView, RedirectView

from accounts.views import SignupView, LogoutUserView, LoginUserView, ProfileView
from cart.views import CartItemsListView, AddItemView, GetCartItemsTotalQuantity, EmptyCart

urlpatterns = [
                  path('admin/', admin.site.urls),
                  #path('cart', TemplateView.as_view(template_name='cart.html'), name='cart'),
                  path('checkout', TemplateView.as_view(template_name='checkout.html'), name='checkout'),
                  path('contact', TemplateView.as_view(template_name='contact.html'), name='contact'),
                  path('signup', SignupView.as_view(), name='signup'),
                  path('logout', LogoutUserView.as_view(), name='logout'),
                  path('login', LoginUserView.as_view(), name='login'),
                  path('oauth', include('social_django.urls', namespace='social')),
                  path('', RedirectView.as_view(url='shop')),
                  path('shop/', include('product.urls', namespace='shop')),
                  path('profile/', ProfileView.as_view(), name='profile'),
                  #path('cart/', CartItemsListView.as_view(), name='cart'),
                  path(r'cart/', include('cart.urls', namespace='cart')),
                  path(r'orders/', include('orders.urls', namespace='orders')),
                  path('add-product/', AddItemView.as_view(), name='add_item'),
                  #path('cart-items-total-quantity/', GetCartItemsTotalQuantity.as_view(), name='cart-items-quantity'),
                  path('empty-cart/', EmptyCart.as_view(), name='empty-cart'),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
                      path('__debug__/', include(debug_toolbar.urls)),

                      # For django versions before 2.0:
                      # url(r'^__debug__/', include(debug_toolbar.urls)),

                  ] + urlpatterns

orders/urls.py
from django.urls import path
from .views import *

app_name = 'orders'

urlpatterns = [
        path('show/<order_id>/', OrderDetailView.as_view(), name='order_detail'),
        path('create/', OrderCreateView.as_view(), name='order_create'),
        path('', OrderListView.as_view(), name='order_list'),
]

product/urls.py
from django.urls import path

from product.views import MainPageView, ProductListView, ProductDetailView

app_name = 'product'

urlpatterns = (
    path('', MainPageView.as_view(), name='main'),
    path('all/', ProductListView.as_view(), name='products-list'),
    path('product/<int:pk>/about', ProductDetailView.as_view(), name='about'),
)

core/models.py
from django.db import models

# Create your models here.

core/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>

    <title>Midgard</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Poppins:200,300,400,500,600,700,800&display=swap"
          rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Amatic+SC:400,700&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'css/open-iconic-bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">

    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">

    <link rel="stylesheet" href="{% static 'css/aos.css' %}">

    <link rel="stylesheet" href="{% static 'css/ionicons.min.css' %}">

    <link rel="stylesheet" href="{% static 'css/bootstrap-datepicker.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery.timepicker.css' %}">


    <link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'css/icomoon.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
</head>
<body class="goto-here">
<div class="py-1 bg-primary">
    <div class="container">
        <div class="row no-gutters d-flex align-items-start align-items-center px-md-0">
            <div class="col-lg-12 d-block">
                <div class="row d-flex">
                    <div class="col-md pr-4 d-flex topper align-items-center">
                        <div class="icon mr-2 d-flex justify-content-center align-items-center"><span
                                class="icon-paper-plane"></span></div>
                        <span class="text">Food delivery Midgard</span>
                    </div>
                    <div class="col-md pr-4 d-flex topper align-items-center">

                        <span class="text">hillel</span>
                    </div>
                    <div class="col-md-5 pr-4 d-flex topper align-items-center text-lg-right">
                        <span class="text">Группа №2</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
    <div class="container">
        <a class="navbar-brand" href="{% url 'shop:main' %}">Midgard</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav"
                aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="oi oi-menu"></span> Menu
        </button>

        <div class="collapse navbar-collapse" id="ftco-nav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active"><a href="{% url 'shop:main' %}" class="nav-link">Home</a></li>
                <li class="nav-item dropdown">
                    <a class="nav-link" href="{% url 'shop:products-list' %}"
                       aria-haspopup="true" aria-expanded="false">Shop</a>
                </li>
                <li class="nav-item"><a href="{% url 'contact' %}" class="nav-link">Contact</a></li>
                <li class="nav-item"><a href="{% url 'orders:order_list' %}" class="nav-link">My Orders</a></li>
                <li class="nav-item cta cta-colored"><a href="{% url 'cart:cart_detail' %}" class="nav-link"><span
                        class="icon-shopping_cart"></span>[<span id="cart_total_items_quantity">0</span>]</a></li>
                {% if user.is_authenticated %}

                    <li class="nav-item"><a href="{% url 'profile' %}"
                                            class="nav-link">{{ user.name|default:user.email }}</a></li>

                    <li class="nav-item"><a href="javascript:{document.getElementById('logout').submit()}"
                                            class="nav-link">Выйти</a></li>
                    <form id="logout" method="POST" action="{% url 'logout' %}">
                        {% csrf_token %}
                        <input type="hidden">
                    </form>
                {% else %}
                    <li class="nav-item"><a href="{% url 'login' %}" class="nav-link">Войти</a></li>
                {% endif %}

            </ul>
        </div>
    </div>
</nav>
<!-- END nav -->

{% block content %}

{% endblock %}

<section class="ftco-section ftco-no-pt ftco-no-pb py-5 bg-light">
    <div class="container py-4">
        <div class="row d-flex justify-content-center py-5">
            <div class="col-md-6">
                <h2 style="font-size: 22px;" class="mb-0">Subcribe to our Newsletter</h2>
                <span>Get e-mail updates about our latest shops and special offers</span>
            </div>
            <div class="col-md-6 d-flex align-items-center">
                <form action="#" class="subscribe-form">
                    <div class="form-group d-flex">
                        <input type="text" class="form-control" placeholder="Enter email address">
                        <input type="submit" value="Subscribe" class="submit px-3">
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>
<footer class="ftco-footer ftco-section">
    <div class="container">
        <div class="row">
            <div class="mouse">
                <a href="#" class="mouse-icon">
                    <div class="mouse-wheel"><span class="ion-ios-arrow-up"></span></div>
                </a>
            </div>
        </div>
        <div class="row mb-5">
            <div class="col-md">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">Midgard</h2>
                    <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia.</p>
                    <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-5">
                        <li class="ftco-animate"><a href="#"><span class="icon-twitter"></span></a></li>
                        <li class="ftco-animate"><a href="#"><span class="icon-facebook"></span></a></li>
                        <li class="ftco-animate"><a href="#"><span class="icon-instagram"></span></a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md">
                <div class="ftco-footer-widget mb-4 ml-md-5">
                    <h2 class="ftco-heading-2">Menu</h2>
                    <ul class="list-unstyled">
                        <li><a href="#" class="py-2 d-block">Shop</a></li>
                        <li><a href="#" class="py-2 d-block">About</a></li>
                        <li><a href="#" class="py-2 d-block">Journal</a></li>
                        <li><a href="#" class="py-2 d-block">Contact Us</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md-4">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">Help</h2>
                    <div class="d-flex">
                        <ul class="list-unstyled mr-l-5 pr-l-3 mr-4">
                            <li><a href="#" class="py-2 d-block">Shipping Information</a></li>
                            <li><a href="#" class="py-2 d-block">Returns &amp; Exchange</a></li>
                            <li><a href="#" class="py-2 d-block">Terms &amp; Conditions</a></li>
                            <li><a href="#" class="py-2 d-block">Privacy Policy</a></li>
                        </ul>
                        <ul class="list-unstyled">
                            <li><a href="#" class="py-2 d-block">FAQs</a></li>
                            <li><a href="#" class="py-2 d-block">Contact</a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-md">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">Have a Questions?</h2>
                    <div class="block-23 mb-3">
                        <ul>
                            <li><span class="icon icon-map-marker"></span><span class="text">203 Fake St. Mountain View, San Francisco, California, USA</span>
                            </li>
                            <li><a href="#"><span class="icon icon-phone"></span><span
                                    class="text">+2 392 3929 210</span></a></li>
                            <li><a href="#"><span class="icon icon-envelope"></span><span class="text">info@yourdomain.com</span></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 text-center">

                <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    Copyright &copy;<script>document.write(new Date().getFullYear());</script>
                    All rights reserved | This template is made with <i class="icon-heart color-danger"
                                                                        aria-hidden="true"></i> by <a
                            href="https://colorlib.com" target="_blank">Colorlib</a>
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                </p>
            </div>
        </div>
    </div>
</footer>


<!-- loader -->
<div id="ftco-loader" class="show fullscreen">
    <svg class="circular" width="48px" height="48px">
        <circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/>
        <circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10"
                stroke="#F96D00"/>
    </svg>
</div>


<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/jquery-migrate-3.0.1.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
<script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
<script src="{% static 'js/jquery.stellar.min.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'js/aos.js' %}"></script>
<script src="{% static 'js/jquery.animateNumber.min.js' %}"></script>
<script src="{% static 'js/bootstrap-datepicker.js' %}"></script>
<script src="{% static 'js/scrollax.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>

<script>
    $(document).ready(function () {

        var quantitiy = 0;
        $('.quantity-right-plus').click(function (e) {

            // Stop acting like a button
            e.preventDefault();
            // Get the field name
            var quantity = parseInt($('#quantity').val());

            // If is not undefined

            $('#quantity').val(quantity + 1);


            // Increment

        });

        $('.quantity-left-minus').click(function (e) {
            // Stop acting like a button
            e.preventDefault();
            // Get the field name
            var quantity = parseInt($('#quantity').val());

            // If is not undefined

            // Increment
            if (quantity > 0) {
                $('#quantity').val(quantity - 1);
            }
        });

    });
</script>

<script type="text/javascript">
    $(document).ready(function () {
        $.ajax({
            type: 'GET',
            async: true,
            {# url: '{% url "cart:cart-items-quantity" %}', #}
            data: {},
            success: function (data) {
                $("#cart_total_items_quantity").text(data['cart_total_items_quantity']);
            },
            dataType: 'json',
        });
    });
</script>

{% block scripts %}
{% endblock %}

</body>
</html>

core/templates/checkout.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <div class="hero-wrap hero-bread" style="background-image: url({% static 'images/bg_1.jpg' %});">
      <div class="container">
        <div class="row no-gutters slider-text align-items-center justify-content-center">
          <div class="col-md-9 ftco-animate text-center">
          	<p class="breadcrumbs"><span class="mr-2"><a href="main_page.html">Home</a></span> <span>Checkout</span></p>
            <h1 class="mb-0 bread">Checkout</h1>
          </div>
        </div>
      </div>
    </div>

    <section class="ftco-section">
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-xl-7 ftco-animate">
						<form action="#" class="billing-form">
							<h3 class="mb-4 billing-heading">Billing Details</h3>
	          	<div class="row align-items-end">
	          		<div class="col-md-6">
	                <div class="form-group">
	                	<label for="firstname">Firt Name</label>
	                  <input type="text" class="form-control" placeholder="">
	                </div>
	              </div>
	              <div class="col-md-6">
	                <div class="form-group">
	                	<label for="lastname">Last Name</label>
	                  <input type="text" class="form-control" placeholder="">
	                </div>
                </div>
                <div class="w-100"></div>
		            <div class="col-md-12">
		            	<div class="form-group">
		            		<label for="country">State / Country</label>
		            		<div class="select-wrap">
		                  <div class="icon"><span class="ion-ios-arrow-down"></span></div>
		                  <select name="" id="" class="form-control">
		                  	<option value="">France</option>
		                    <option value="">Italy</option>
		                    <option value="">Philippines</option>
		                    <option value="">South Korea</option>
		                    <option value="">Hongkong</option>
		                    <option value="">Japan</option>
		                  </select>
		                </div>
		            	</div>
		            </div>
		            <div class="w-100"></div>
		            <div class="col-md-6">
		            	<div class="form-group">
	                	<label for="streetaddress">Street Address</label>
	                  <input type="text" class="form-control" placeholder="House number and street name">
	                </div>
		            </div>
		            <div class="col-md-6">
		            	<div class="form-group">
	                  <input type="text" class="form-control" placeholder="Appartment, suite, unit etc: (optional)">
	                </div>
		            </div>
		            <div class="w-100"></div>
		            <div class="col-md-6">
		            	<div class="form-group">
	                	<label for="towncity">Town / City</label>
	                  <input type="text" class="form-control" placeholder="">
	                </div>
		            </div>
		            <div class="col-md-6">
		            	<div class="form-group">
		            		<label for="postcodezip">Postcode / ZIP *</label>
	                  <input type="text" class="form-control" placeholder="">
	                </div>
		            </div>
		            <div class="w-100"></div>
		            <div class="col-md-6">
	                <div class="form-group">
	                	<label for="phone">Phone</label>
	                  <input type="text" class="form-control" placeholder="">
	                </div>
	              </div>
	              <div class="col-md-6">
	                <div class="form-group">
	                	<label for="emailaddress">Email Address</label>
	                  <input type="text" class="form-control" placeholder="">
	                </div>
                </div>
                <div class="w-100"></div>
                <div class="col-md-12">
                	<div class="form-group mt-4">
										<div class="radio">
										  <label class="mr-3"><input type="radio" name="optradio"> Create an Account? </label>
										  <label><input type="radio" name="optradio"> Ship to different address</label>
										</div>
									</div>
                </div>
	            </div>
	          </form><!-- END -->
					</div>
					<div class="col-xl-5">
	          <div class="row mt-5 pt-3">
	          	<div class="col-md-12 d-flex mb-5">
	          		<div class="cart-detail cart-total p-3 p-md-4">
	          			<h3 class="billing-heading mb-4">Cart Total</h3>
	          			<p class="d-flex">
		    						<span>Subtotal</span>
		    						<span>$20.60</span>
		    					</p>
		    					<p class="d-flex">
		    						<span>Delivery</span>
		    						<span>$0.00</span>
		    					</p>
		    					<p class="d-flex">
		    						<span>Discount</span>
		    						<span>$3.00</span>
		    					</p>
		    					<hr>
		    					<p class="d-flex total-price">
		    						<span>Total</span>
		    						<span>$17.60</span>
		    					</p>
								</div>
	          	</div>
	          	<div class="col-md-12">
	          		<div class="cart-detail p-3 p-md-4">
	          			<h3 class="billing-heading mb-4">Payment Method</h3>
									<div class="form-group">
										<div class="col-md-12">
											<div class="radio">
											   <label><input type="radio" name="optradio" class="mr-2"> Direct Bank Tranfer</label>
											</div>
										</div>
									</div>
									<div class="form-group">
										<div class="col-md-12">
											<div class="radio">
											   <label><input type="radio" name="optradio" class="mr-2"> Check Payment</label>
											</div>
										</div>
									</div>
									<div class="form-group">
										<div class="col-md-12">
											<div class="radio">
											   <label><input type="radio" name="optradio" class="mr-2"> Paypal</label>
											</div>
										</div>
									</div>
									<div class="form-group">
										<div class="col-md-12">
											<div class="checkbox">
											   <label><input type="checkbox" value="" class="mr-2"> I have read and accept the terms and conditions</label>
											</div>
										</div>
									</div>
									<p><a href="#"class="btn btn-primary py-3 px-4">Place an order</a></p>
								</div>
	          	</div>
	          </div>
          </div> <!-- .col-md-8 -->
        </div>
      </div>
    </section> <!-- .section -->

{% endblock %}

core/templates/product-single.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<!--
    <div class="hero-wrap hero-bread" style="background-image: url({% static 'images/bg_1.jpg' %});">
        <div class="container">
            <div class="row no-gutters slider-text align-items-center justify-content-center">
                <div class="col-md-9 ftco-animate text-center">
                    <p class="breadcrumbs"><span class="mr-2"><a href="main_page.html">Home</a></span> <span
                            class="mr-2"><a href="main_page.html">Product</a></span> <span>Product Single</span></p>
                    <h1 class="mb-0 bread">Product Single</h1>
                </div>
            </div>
        </div>
    </div>
-->
    <section class="ftco-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 mb-5 ftco-animate">
                    <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
                        <div class="carousel-inner">
                            <div class="carousel-item active">
                                <a href="{{ product.main_photo.url }}" class="image-popup"><img
                                        src="{{ product.main_photo.url }}" class="img-fluid" alt="No image"></a>
                            </div>
                            {% for image in product.additional_images.all %}
                                <div class="carousel-item">
                                    <a href="{{ image.image.url }}" class="image-popup"><img
                                            src="{{ image.image.url }}" class="img-fluid" alt="No image"></a>
                                </div>
                            {% endfor %}
                        </div>
                        <a class="carousel-control-prev" href="#carouselExampleControls" role="button"
                           data-slide="prev">
                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                            <span class="sr-only">Previous</span>
                        </a>
                        <a class="carousel-control-next" href="#carouselExampleControls" role="button"
                           data-slide="next">
                            <span class="carousel-control-next-icon" aria-hidden="true"></span>
                            <span class="sr-only">Next</span>
                        </a>
                    </div>
                </div>
                <div class="col-lg-6 product-details pl-md-5 ftco-animate">
                    <h3>{{ product.name }}</h3>
                    <p class="price"><span>${{ product.price }}</span></p>
                    <p>
                        {{ product.full_description }}
                    </p>
                    <p>
                        Белки: {{ product.proteins }}
                    </p>
                    <p>
                        Жиры: {{ product.fats }}
                    </p>
                    <p>
                        Углеводы: {{ product.carbohydrates }}
                    </p>
                    <p><a href="{% url 'cart:cart_add' product.id %}" class="btn btn-black">Добавить в корзину
                    </a></p>
                    <div id="unauthorized_error" class="alert alert-danger" role="alert">
                        Только залогиненые пользователи могут добавлять товары в корзину. <a href="{% url 'login' %}" class="alert-link">Войти</a>
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock %}

{% block scripts %}

    <script type="text/javascript">
        $(document).ready(function () {
            $("#unauthorized_error").hide();
            $("#add-to-cart").click(function () {
                $.ajax({
                    type: 'GET',
                    async: true,
                    url: '{% url "cart:add_item" %}',
                    data: {
                        'product_id': {{ product.id }}
                    },
                    success: function (data) {
                        if (data['cart_total_items_quantity']) {
                            $("#cart_total_items_quantity").text(data['cart_total_items_quantity']);
                        } else if (data['unauthorized_error'] == 'true') {
                            $("#unauthorized_error").show();
                        }

                    },
                    dataType: 'json',
                });
            });
        });
    </script>

{% endblock %}

core/templates/shop.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}

{% block content %}

    <div class="hero-wrap hero-bread" style="background-image: url({% static 'images/bg_1.jpg' %});">
        <div class="container">
            <div class="row no-gutters slider-text align-items-center justify-content-center">
                <div class="col-md-9 ftco-animate text-center">
                    <p class="breadcrumbs"><span class="mr-2"><a href="main_page.html">Home</a></span>
                        <span>Products</span></p>
                    <h1 class="mb-0 bread">Products</h1>
                </div>
            </div>
        </div>
    </div>
    <section class="ftco-section">

        <div class="container">
            <ul class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="dropdown04" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">Отфильтровать по категории</a>
                <li class="dropdown-menu" aria-labelledby="dropdown04">
                    <form action="{% url 'product:products-list' %} " method="get">
                        <a href="{% url 'product:products-list' %}" class="btn btn-block border-bottom border-top">Сбросить</a>
                        {% for category in categories %}
                            <input type="submit" class="btn btn-block border-bottom border-top" value="{{ category.name }}" name="category">
                        {% endfor %}
                    </form>
                </li>
            </ul>

            <div class="row">
                {% for product in products %}
                    <div class="col-md-6 col-lg-3 ftco-animate">
                        <div class="product">
                            <a href="{% url 'product:about' product.id %}" class="img-prod"><img
                                    class="img-fluid"
                                    src="{{ product.main_photo.url }}"
                                    alt="No photo">
                                <div class="overlay"></div>
                            </a>
                            <div class="text py-3 pb-4 px-3 text-center">
                                <h3><a target="_blank" href="{% url 'product:about' product.id %}">{{ product.name }}</a>
                                </h3>
                                <p class="text-muted">{{ product.short_description }}</p>
                                <div class="d-flex">
                                    <div class="pricing">
                                        <p class="price"><span
                                                class="price-sale">${{ product.price }}</span>
                                        </p>
                                    </div>
                                </div>
                                <div class="bottom-area d-flex px-3">
                                    <div class="m-auto d-flex">
                                        <a href="{% url 'cart:cart_add' product.id %}">+</a>

                                       {# <a href="#add_to_cart" #}
                                       {#    class="add-to-cart d-flex justify-content-center align-items-center text-center"> #}
                                       {#     <span><i class="ion-ios-cart">+</i></span> #}
                                       {# </a> #}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% empty %}
                    <h2 class="mb-4 border-bottom border-success mx-auto ftco-animate">No products yet</h2>
                {% endfor %}
            </div>
        </div>
        <div class="container">
            <div class="row">

                <div class="row mt-5 mx-auto">
                    <div class="col text-center">
                        {% if paginator.num_pages > 1 %}
                            {% bootstrap_pagination page_obj %}
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </section>


{% endblock %}